"use client";
import { Head } from "next/document";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "../redux/providers";
import NavBarTop from "../components/NavBarTop/NavBarTop";
import NavBarFooter from "../components/navBarFooter/NavBarFooter";
import { Josefin_Sans } from "next/font/google";
import { usePathname } from "next/navigation";
/* import AuthProvider from "../features/AuthProvider"; */

export const metadata = {
  title: "Go-Trip",
  description: "Generated by henryTeam#14",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  // console.log('Ruta actual:', pathname); //Check Ruta actual

  const renderNavBarTop = pathname !== "/register" && pathname !== "/login";
  const renderNavBarFooter = pathname !== "/register" && pathname !== "/login";

  return (
    <html lang="en">
      <Providers>
        <Head>
          <link
            href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;500;600;700&family=Nunito:wght@500;700;900&display=swap"
            rel="stylesheet"
          />
        </Head>

        <body>
          {renderNavBarTop && <NavBarTop />}
          {children}
          {renderNavBarFooter && <NavBarFooter />}
        </body>
      </Providers>
    </html>
  );
}
