"use client";
import "./globals.css";
import { Josefin_Sans, Poppins } from "next/font/google";
import Providers from "../redux/providers";
import NavBarTop from "../components/NavBarTop/NavBarTop";
import NavBarFooter from "../components/navBarFooter/NavBarFooter";
import { usePathname } from "next/navigation";
/* import AuthProvider from "../features/AuthProvider"; */

const josefin_sans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin",
  weight: ["300", "500", "700"],
});

const nunito = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "500", "700"],
});

export const metadata = {
  title: "Go-Trip",
  description: "Generated by henryTeam#14",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  // console.log('Ruta actual:', pathname); //Check Ruta actual

  const renderNavBarTop = pathname !== "/register" && pathname !== "/login";
  const renderNavBarFooter = pathname !== "/register" && pathname !== "/login";

  return (
    <html lang="en">
      <Providers>
        <body className=" font-josefin text-neutral-700">
          {renderNavBarTop && <NavBarTop />}
          {children}
          {renderNavBarFooter && <NavBarFooter />}
        </body>
      </Providers>
    </html>
  );
}
